version: "3"
services:
  postgres-db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - '5432:5432'
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: postgres
            password: 12345
    links:
      - postgres-db
  graphql:
    container_name: graphqlAPP
    restart: always
    build: rankif-graphql-server
    ports:
    - "4000:4000"
    links:
      - prisma