apiVersion: v1
items:
- apiVersion : apps/v1beta1
  kind: Deployment
  metadata:
    name: graphql
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: graphql
      spec:
        containers:
          - name: graphql
            image: rankif.azurecr.io/graphql
            ports:
            - containerPort: 4000

- apiVersion : apps/v1beta1
  kind: Deployment
  metadata:
    name: graphql
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres-db
    template:
      metadata:
        labels:
          app: postgres-db
      spec:
        containers:
          - env:
              - name: POSTGRES_PASSWORD
                value: "12345"
              - name: POSTGRES_USER
                value: postgres
            image: postgres:10.3
            imagePullPolicy: ""
            name: postgres-db
            ports:
              - containerPort: 5432
            resources: {}
            volumeMounts:
              - mountPath: /data/postgres
                name: postgres-db-claim0
        restartPolicy: Always
        serviceAccountName: ""
        volumes:
          - name: postgres-db-claim0
            persistentVolumeClaim:
              claimName: postgres-db-claim0

- apiVersion: apps/v1beta1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: postgres-db-claim0
    name: postgres-db-claim0
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: prisma
    name: prisma
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: prisma
    template:
      metadata:
        labels:
          app: prisma
      spec:
        containers:
          - env:
              - name: PRISMA_CONFIG
                value: |
                  port: 4466
                  databases:
                    default:
                      connector: postgres
                      host: postgres-db
                      port: 5432
                      user: postgres
                      password: 12345
            image: prismagraphql/prisma:1.34
            imagePullPolicy: ""
            name: prisma
            ports:
              - containerPort: 4466
            resources: {}