apiVersion: v1
kind: Service
metadata:
    name: "rankifback"
    labels:
        app: "rankifback"
spec:
    type: LoadBalancer
    ports:
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "rankifback"