apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
        name: graphql
  spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: graphql

- apiVersion: v1
  kind: Service
  metadata:
    name: postgres-db
  spec:
    ports:
        - name: "5432"
            port: 5432
            targetPort: 5432
    selector:
        app: postgres-db

- apiVersion: v1
  kind: Service
  metadata:
    name: prisma
  spec:
    ports:
        - name: "4466"
        port: 4466
        targetPort: 4466
    selector:
        app: prisma