apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: graphql 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: graphql 
    spec:
      containers:
        - name: graphql 
          image: rankif.azurecr.io/graphql
          ports:
          - containerPort: 80