apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      creationTimestamp: null
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: "12345"
            - name: POSTGRES_USER
              value: postgres
          image: postgres:10.3
          imagePullPolicy: ""
          name: postgres-db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /data/postgres
              name: postgres-db-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: postgres-db-claim0
          persistentVolumeClaim:
            claimName: postgres-db-claim0